# Generated by Django 5.2.9 on 2026-08-04 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("unit", models.CharField(default="piece", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "consumable",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaitInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("straw", "Semen straw"), ("consumable", "Consumable")],
                        max_length=12,
                    ),
                ),
                (
                    "product_ref_id",
                    models.BigIntegerField(
                        help_text="SemenBatch.id for straws, Consumable.id for consumables."
                    ),
                ),
                ("qty_available", models.IntegerField(default=0)),
                (
                    "mait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to="masterdata.mait",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mait inventory",
                "db_table": "mait_inventory",
            },
        ),
        migrations.CreateModel(
            name="MaitInventoryLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("issue", "Issued to Mait"),
                            ("consume", "Consumed by AI event"),
                            ("return", "Returned to store"),
                            ("adjustment", "Manual adjustment"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "qty",
                    models.IntegerField(help_text="Positive for credits, negative for debits."),
                ),
                (
                    "balance_after",
                    models.IntegerField(
                        help_text="Balance immediately after this movement — makes the ledger auditable without replaying every prior row."
                    ),
                ),
                (
                    "ref_type",
                    models.CharField(
                        choices=[
                            ("indent", "Indent"),
                            ("ai_event", "AI event"),
                            ("manual", "Manual adjustment"),
                        ],
                        max_length=12,
                    ),
                ),
                ("ref_id", models.BigIntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="inventory.maitinventory",
                    ),
                ),
            ],
            options={
                "db_table": "mait_inventory_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SemenBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unique_straw_no", models.CharField(db_index=True, max_length=30, unique=True)),
                ("breed", models.CharField(db_index=True, max_length=30)),
                ("bull_id", models.CharField(blank=True, max_length=30)),
                ("semen_station", models.CharField(blank=True, max_length=100)),
                ("received_date", models.DateField(blank=True, null=True)),
                (
                    "is_consumed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Set when an AI event completes against this straw. Never reset.",
                    ),
                ),
            ],
            options={
                "db_table": "semen_batch",
                "ordering": ["-received_date", "unique_straw_no"],
                "indexes": [
                    models.Index(fields=["breed", "is_consumed"], name="straw_breed_consumed_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="maitinventory",
            index=models.Index(fields=["mait", "product_type"], name="inventory_mait_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="maitinventory",
            constraint=models.UniqueConstraint(
                fields=("mait", "product_type", "product_ref_id"), name="uniq_mait_product_balance"
            ),
        ),
        migrations.AddConstraint(
            model_name="maitinventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_available__gte", 0)), name="inventory_qty_never_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="maitinventoryledger",
            index=models.Index(fields=["inventory", "-created_at"], name="ledger_inv_time_idx"),
        ),
        migrations.AddIndex(
            model_name="maitinventoryledger",
            index=models.Index(fields=["ref_type", "ref_id"], name="ledger_ref_idx"),
        ),
    ]
