# Generated by Django 5.2.16 on 2026-08-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consumable",
            options={"ordering": ["category", "display_order", "name"]},
        ),
        migrations.AddField(
            model_name="consumable",
            name="category",
            field=models.CharField(
                choices=[("consumable", "Consumable"), ("asset", "Equipment")],
                db_index=True,
                default="consumable",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="consumable",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
