# Generated by Django 5.2.16 on 2026-08-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_seed_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="semenbatch",
            name="is_unnumbered",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Issued as a quantity of a breed rather than by number, so this row is a placeholder carrying a generated number. The Mait supplies the real one at the AI step, which claims this row and clears the flag (SRS §6.3 step 4).",
            ),
        ),
    ]
