# Generated by Django 5.2.16 on 2026-08-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_semenbatch_is_unnumbered"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumable",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost of one unit, in rupees. Zero means not priced — the catalogue is maintained by hand and a rate nobody has entered yet must not read as free.",
                max_digits=10,
            ),
        ),
    ]
