# Generated by Django 5.2.9 on 2026-08-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreedConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal_type",
                    models.CharField(
                        choices=[("COW", "Cow"), ("BUFF", "Buffalo")], db_index=True, max_length=4
                    ),
                ),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=60)),
                (
                    "name_hi",
                    models.CharField(
                        blank=True,
                        help_text="Devanagari label for the Hindi toggle.",
                        max_length=60,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "breed_config",
                "ordering": ["animal_type", "display_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("animal_type", "code"), name="uniq_breed_per_animal_type"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("member", "Member"), ("non_member", "Non-member")],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "animal_type",
                    models.CharField(
                        choices=[("COW", "Cow"), ("BUFF", "Buffalo")], db_index=True, max_length=4
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        help_text="BreedConfig.code at time of capture.", max_length=30
                    ),
                ),
                (
                    "ear_tag_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optional, but unique across the platform when present (SRS §6.3 step 3).",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animals",
                        to="masterdata.member",
                    ),
                ),
                (
                    "non_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animals",
                        to="masterdata.nonmember",
                    ),
                ),
            ],
            options={
                "db_table": "animal",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["member", "animal_type"], name="animal_member_type_idx"),
                    models.Index(fields=["non_member"], name="animal_nonmember_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("member__isnull", False), ("non_member__isnull", True)),
                            models.Q(("member__isnull", True), ("non_member__isnull", False)),
                            _connector="OR",
                        ),
                        name="animal_exactly_one_owner",
                    )
                ],
            },
        ),
    ]
