# Generated by Django 5.2.16 on 2026-08-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_seed_breeds"),
    ]

    operations = [
        migrations.AddField(
            model_name="breedconfig",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost of one straw of this breed, in rupees. Zero means not priced — the list is maintained by hand and a rate nobody has entered must not read as free.",
                max_digits=10,
            ),
        ),
    ]
