# Generated by Django 5.2.16 on 2026-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_breedconfig_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.CharField(
                blank=True,
                default="",
                help_text="BreedConfig.code, and the animal's own breed — not the semen's. Optional, because a Mait registering a cow in a yard often cannot say what she is, and a flow that insists would collect guesses. Fill it in later from the portal or the animal endpoint.",
                max_length=30,
            ),
        ),
    ]
