# Generated by Django 5.2.16 on 2026-08-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0004_alter_animal_breed"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="photo_url",
            field=models.CharField(
                blank=True,
                help_text="A portrait taken when she was registered, so the Mait recognises her on the next visit. Most animals here carry no ear tag, and 'the black one' is not a record.",
                max_length=255,
            ),
        ),
    ]
