# Generated by Django 5.2.16 on 2026-08-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0005_animal_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="breedconfig",
            name="non_member_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="What a non-member pays the Mait on the spot, in rupees. Kept apart from the member rate because the two are different prices for the same service: one is settled against a milk payout the dairy already owes, the other is cash in a yard.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="breedconfig",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="What a member is charged for one insemination of this breed, in rupees. She hands over nothing: the dairy deducts it from her milk payment at the next payout. Zero means not priced — the list is maintained by hand and a rate nobody has entered must not read as free.",
                max_digits=10,
            ),
        ),
    ]
