# Generated by Django 5.2.16 on 2026-09-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0006_breedconfig_non_member_rate_alter_breedconfig_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="client_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Device-generated id for a registration that may be retried (ADR 0003).",
                null=True,
                unique=True,
            ),
        ),
    ]
