# Generated by Django 5.2.9 on 2026-08-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("highest_day", "Highest single day"),
                            ("highest_month", "Highest single month"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
                ("occurred_on", models.DateField(blank=True, null=True)),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Display label, e.g. 'March 2026'.", max_length=30
                    ),
                ),
            ],
            options={
                "db_table": "platform_milestone",
            },
        ),
        migrations.CreateModel(
            name="DailyAIAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "district_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Denormalised from the MPP so district filters avoid a join.",
                        max_length=10,
                    ),
                ),
                ("ai_count", models.PositiveIntegerField(default=0)),
                ("member_ai_count", models.PositiveIntegerField(default=0)),
                ("non_member_ai_count", models.PositiveIntegerField(default=0)),
                ("distinct_members_served", models.PositiveIntegerField(default=0)),
                (
                    "amount_collected",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cod_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("online_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "mait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_aggregates",
                        to="masterdata.mait",
                    ),
                ),
                (
                    "mpp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_aggregates",
                        to="masterdata.mpp",
                    ),
                ),
            ],
            options={
                "db_table": "daily_ai_aggregate",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date", "district_code"], name="agg_date_district_idx"),
                    models.Index(fields=["mait", "date"], name="agg_mait_date_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "mpp", "mait"), name="uniq_daily_aggregate_slice"
                    )
                ],
            },
        ),
    ]
