# Generated by Django 5.2.16 on 2026-09-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("masterdata", "0011_zone_zoneplant"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyaiaggregate",
            name="plant_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The BMC/MCC, denormalised from the MPP for the same reason as the district — it is what a zone is a set of, so every zone-scoped read filters on it.",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="dailyaiaggregate",
            index=models.Index(fields=["date", "plant_code"], name="agg_date_plant_idx"),
        ),
    ]
