# Generated by Django 5.2.9 on 2026-08-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndentEasyWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delivery_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("indent_easy_ref_no", models.CharField(db_index=True, max_length=50)),
                ("payload", models.JSONField(default=dict)),
                ("signature_valid", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("duplicate", "Duplicate — ignored"),
                            ("failed", "Processing failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=12,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "indent_easy_webhook_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IndentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("straw", "Semen straw"), ("consumable", "Consumable")],
                        max_length=12,
                    ),
                ),
                (
                    "product_ref_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Consumable.id where applicable. Straw requests are by breed, not by straw — the specific straws are chosen at issue time.",
                        null=True,
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        blank=True, help_text="For straw requests (SRS §6.6.1).", max_length=30
                    ),
                ),
                ("qty_requested", models.PositiveIntegerField()),
                ("qty_issued", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("issued", "Issued"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                    ),
                ),
                (
                    "indent_easy_ref_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Reference returned by Indent Easy; dedupes GRN callbacks (SRS §6.6.5).",
                        max_length=50,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Not yet pushed"),
                            ("synced", "Pushed to Indent Easy"),
                            ("failed", "Push failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("sync_attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_sync_error", models.CharField(blank=True, max_length=255)),
                ("requested_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "mait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indents",
                        to="masterdata.mait",
                    ),
                ),
            ],
            options={
                "db_table": "indent_request",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(fields=["mait", "-requested_at"], name="indent_mait_time_idx"),
                    models.Index(fields=["status", "-requested_at"], name="indent_status_time_idx"),
                    models.Index(fields=["sync_status", "sync_attempts"], name="indent_sync_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("qty_requested__gt", 0)),
                        name="indent_qty_requested_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("qty_issued__lte", models.F("qty_requested"))),
                        name="indent_issued_not_over_requested",
                    ),
                ],
            },
        ),
    ]
