# Generated by Django 5.2.16 on 2026-08-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indentrequest",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Mait confirmed they collected it. Stock is credited at issue, not here — this is the acknowledgement that the goods reached them, and the only step in the chain the Mait owns.",
                null=True,
            ),
        ),
    ]
