# Generated by Django 5.2.16 on 2026-08-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indents", "0002_indentrequest_received_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="indentrequest",
            name="issued_straw_numbers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Straws set aside for this indent at issue, credited on collection. Held here rather than as stock because they are not the Mait's until they collect them.",
            ),
        ),
        migrations.AlterField(
            model_name="indentrequest",
            name="received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Mait confirmed they collected it. This is where stock is credited — between issue and collection the goods are at the depot, not in the Mait's flask, and a balance that says otherwise would let them start an AI they cannot finish.",
                null=True,
            ),
        ),
    ]
