# Generated by Django 5.2.16 on 2026-09-11 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indents", "0003_indentrequest_issued_straw_numbers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndentHandover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty", models.PositiveIntegerField()),
                (
                    "collection_code",
                    models.CharField(
                        help_text="Read aloud by the keeper and typed in by the Mait. Never sent to the Mait's app — a code the handset already knows proves nothing.",
                        max_length=8,
                    ),
                ),
                ("code_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "flask_checked",
                    models.BooleanField(
                        default=False,
                        help_text="The keeper checked the flask's temperature before straws left the store.",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("collected_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The Mait never collected it and the keeper put the stock back. The quantity goes back to being open on the indent.",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "indent_handover",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.AddField(
            model_name="indentrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="indentrequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who agreed to it — the zonal manager, normally. The store keeper reads this before handing anything over.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_indents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
