# Generated by Django 5.2.16 on 2026-09-11 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indents", "0004_indenthandover_indentrequest_approved_at_and_more"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="indentrequest",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="The depot that hands this over. Worked out from the Mait's BMC/MCCs when the indent is raised or approved; empty where no store serves them yet, which leaves the portal's own Issue as the way out.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="indents",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="indenthandover",
            name="indent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="handovers",
                to="indents.indentrequest",
            ),
        ),
        migrations.AddField(
            model_name="indenthandover",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handovers_issued",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="indenthandover",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="handovers",
                to="stores.store",
            ),
        ),
        migrations.AddIndex(
            model_name="indenthandover",
            index=models.Index(fields=["store", "-issued_at"], name="handover_store_time_idx"),
        ),
        migrations.AddConstraint(
            model_name="indenthandover",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty__gt", 0)), name="handover_qty_positive"
            ),
        ),
    ]
