# Generated by Django 5.2.16 on 2026-09-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indents", "0005_indentrequest_store_indenthandover_indent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IndentEasyWebhookEvent",
        ),
        migrations.RemoveIndex(
            model_name="indentrequest",
            name="indent_sync_idx",
        ),
        migrations.RemoveField(
            model_name="indentrequest",
            name="indent_easy_ref_no",
        ),
        migrations.RemoveField(
            model_name="indentrequest",
            name="last_sync_error",
        ),
        migrations.RemoveField(
            model_name="indentrequest",
            name="sync_attempts",
        ),
        migrations.RemoveField(
            model_name="indentrequest",
            name="sync_status",
        ),
    ]
