# Generated by Django 5.2.9 on 2026-08-04 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("endpoint", models.CharField(max_length=120)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "idempotency_record",
                "indexes": [models.Index(fields=["expires_at"], name="idem_expiry_idx")],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("state_change", "State change"),
                            ("pii_access", "Full PII access"),
                            ("upload", "Master data upload"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.CharField(db_index=True, max_length=50)),
                (
                    "meta_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Before/after values. PII is stored masked, never in the clear.",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system-initiated actions such as scheduled jobs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "-created_at"],
                        name="audit_entity_time_idx",
                    ),
                    models.Index(fields=["actor", "-created_at"], name="audit_actor_time_idx"),
                ],
            },
        ),
    ]
