# Generated by Django 5.2.16 on 2026-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idempotencyrecord",
            name="key",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("key", "endpoint"), name="idempotency_key_endpoint_uniq"
            ),
        ),
    ]
