# Generated by Django 5.2.9 on 2026-08-04 09:47

import apps.core.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("member", "Member Master"),
                            ("mait", "Mait / Vendor Master"),
                            ("mpp", "MPP / Sahayak Master"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/master-data/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=25,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                (
                    "processed_rows",
                    models.PositiveIntegerField(
                        default=0, help_text="Drives the progress endpoint (SRS §6.1.6)."
                    ),
                ),
                (
                    "error_report",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Row-level failures, downloadable as a report (SRS §6.1.4).",
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="master_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data upload",
                "db_table": "data_upload_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Mait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sahayak_vendor_code",
                    models.CharField(
                        db_index=True,
                        help_text="SAP Sahayak Vendor / Customer ID — the upsert key.",
                        max_length=15,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "mobile_no",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("mobile_no_alt", models.CharField(blank=True, max_length=15)),
                ("pan_no", apps.core.fields.EncryptedCharField(blank=True, max_length=12)),
                ("aadhar_no", apps.core.fields.EncryptedCharField(blank=True, max_length=20)),
                ("bank_account_no", apps.core.fields.EncryptedCharField(blank=True, max_length=30)),
                ("ifsc_code", models.CharField(blank=True, max_length=15)),
                ("gst_no", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Login identity. Null until an Admin activates the account (SRS §6.8.2).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mait_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mait",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MPP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plant_code", models.CharField(blank=True, max_length=10)),
                ("plant_name", models.CharField(blank=True, max_length=100)),
                ("mpp_code", models.CharField(db_index=True, max_length=15, unique=True)),
                ("mpp_name", models.CharField(db_index=True, max_length=150)),
                ("mpp_category", models.CharField(blank=True, max_length=20)),
                ("mpp_sub_category", models.CharField(blank=True, max_length=20)),
                ("state_code", models.CharField(blank=True, db_index=True, max_length=10)),
                ("district_code", models.CharField(blank=True, db_index=True, max_length=10)),
                ("tehsil_code", models.CharField(blank=True, max_length=10)),
                ("panchayat_code", models.CharField(blank=True, max_length=10)),
                ("village_code", models.CharField(blank=True, max_length=10)),
                ("hamlet_code", models.CharField(blank=True, max_length=10)),
                ("mobile_no", models.CharField(blank=True, max_length=15)),
                ("address_line", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("revival_date", models.DateField(blank=True, null=True)),
                (
                    "mait",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assigned Sahayak/Mait. Admin can override the SAP default (SRS §6.2.2).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mpps",
                        to="masterdata.mait",
                    ),
                ),
            ],
            options={
                "verbose_name": "MPP",
                "verbose_name_plural": "MPPs",
                "db_table": "mpp",
                "ordering": ["mpp_name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("member_code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("member_name", models.CharField(db_index=True, max_length=150)),
                ("father_husband_name", models.CharField(blank=True, max_length=150)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=30)),
                ("education", models.CharField(blank=True, max_length=50)),
                (
                    "social_class",
                    models.CharField(
                        blank=True,
                        help_text="SAP 'Class' column — renamed, `class` is a Python keyword.",
                        max_length=30,
                    ),
                ),
                ("sap_vendor_code", models.CharField(blank=True, db_index=True, max_length=20)),
                ("form_no", models.CharField(blank=True, max_length=20)),
                ("folio_no", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "mobile_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Payment authorisation OTPs are sent here (SRS §6.5).",
                        max_length=15,
                    ),
                ),
                ("aadhar_no", apps.core.fields.EncryptedCharField(blank=True, max_length=20)),
                ("cattle_holding", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("bank_ac_no", apps.core.fields.EncryptedCharField(blank=True, max_length=30)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("ifsc_code", models.CharField(blank=True, max_length=15)),
                ("activation_status", models.CharField(blank=True, db_index=True, max_length=20)),
                ("activation_date", models.DateField(blank=True, null=True)),
                ("deactivation_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "mpp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="masterdata.mpp",
                    ),
                ),
            ],
            options={
                "db_table": "member",
                "ordering": ["member_name"],
            },
        ),
        migrations.CreateModel(
            name="NonMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "mobile_no",
                    models.CharField(
                        db_index=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "consent_captured_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the farmer consented to their details being stored.",
                        null=True,
                    ),
                ),
                (
                    "created_by_mait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_non_members",
                        to="masterdata.mait",
                    ),
                ),
                (
                    "mpp",
                    models.ForeignKey(
                        help_text="Nearest/served MPP.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="non_members",
                        to="masterdata.mpp",
                    ),
                ),
            ],
            options={
                "db_table": "non_member",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="mait",
            index=models.Index(fields=["is_active", "name"], name="mait_active_name_idx"),
        ),
        migrations.AddIndex(
            model_name="mpp",
            index=models.Index(fields=["district_code", "is_active"], name="mpp_district_idx"),
        ),
        migrations.AddIndex(
            model_name="mpp",
            index=models.Index(fields=["mait", "is_active"], name="mpp_mait_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["mpp", "member_name"], name="member_mpp_name_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["mpp", "activation_status"], name="member_mpp_status_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["mobile_no"], name="member_mobile_idx"),
        ),
        migrations.AddIndex(
            model_name="nonmember",
            index=models.Index(fields=["mpp", "name"], name="nonmember_mpp_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="nonmember",
            constraint=models.UniqueConstraint(
                fields=("mobile_no", "mpp"), name="uniq_non_member_mobile_per_mpp"
            ),
        ),
    ]
