# Generated by Django 5.2.16 on 2026-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datauploadlog",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("member", "Member Master"),
                    ("mait", "Mait / Vendor Master"),
                    ("mpp", "MPP / Sahayak Master"),
                    ("assignment", "Mait ↔ MPP assignment"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
