# Generated by Django 5.2.16 on 2026-08-07 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0002_alter_datauploadlog_upload_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpp",
            name="sahayak_mobile_no",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="mpp",
            name="sahayak_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="mpp",
            name="sahayak_vendor_code",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="mpp",
            name="mait",
            field=models.ForeignKey(
                blank=True,
                help_text="The Mait covering this MPP (SRS §6.2.2). Set from the assignment sheet, never from the SAP master — the master's Sahayak column is a different person.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mpps",
                to="masterdata.mait",
            ),
        ),
    ]
