# Generated by Django 5.2.16 on 2026-08-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0003_mpp_sahayak_mobile_no_mpp_sahayak_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonmember",
            name="father_husband_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="datauploadlog",
            name="error_report",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Row-level failures, downloadable as a report (SRS §6.1.4). One entry per rejected row up to MAX_ERRORS_STORED — except a whole-file failure, which stores a single explanation and rejects no rows.",
            ),
        ),
    ]
