# Generated by Django 5.2.16 on 2026-08-12 06:49

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0004_nonmember_father_husband_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonmember",
            name="aadhar_no",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=20),
        ),
    ]
