# Generated by Django 5.2.16 on 2026-08-12 07:07

from django.db import migrations, models

from apps.core.fields import pii_lookup_hash

# Rows per pass. Every row has to be decrypted in Python — the ciphertext is opaque to SQL —
# so the whole member table cannot be held in memory at once on a small dyno.
BATCH = 500


def backfill(apps, schema_editor):
    """
    Fingerprint the Aadhaar numbers already on the roll.

    Without this the check that stops a member being registered as a non-member matches
    nothing on day one, which is worse than not having it: it would report every member as
    unknown and quietly wave through exactly the case it exists to catch.

    Members whose SAP row carried no Aadhaar keep an empty hash and are simply not checkable
    by this route — the field is blank for a large part of the roll, and that is a data gap to
    close upstream, not something a migration can invent.
    """
    Member = apps.get_model("masterdata", "Member")

    updates = []
    for member in Member.objects.exclude(aadhar_no="").iterator(chunk_size=BATCH):
        member.aadhar_hash = pii_lookup_hash(member.aadhar_no)
        updates.append(member)
        if len(updates) >= BATCH:
            Member.objects.bulk_update(updates, ["aadhar_hash"])
            updates = []
    if updates:
        Member.objects.bulk_update(updates, ["aadhar_hash"])


def drop(apps, schema_editor):
    """The column goes with the field, so there is nothing to undo beyond that."""


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0005_nonmember_aadhar_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="aadhar_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="nonmember",
            name="aadhar_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.RunPython(backfill, drop),
    ]
