# Generated by Django 5.2.16 on 2026-08-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0006_member_aadhar_hash_nonmember_aadhar_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonmember",
            name="aadhar_back_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="nonmember",
            name="aadhar_front_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="nonmember",
            name="relation",
            field=models.CharField(
                blank=True,
                choices=[("father", "Father"), ("husband", "Husband")],
                help_text="Whether father_husband_name is her father or her husband.",
                max_length=10,
            ),
        ),
    ]
