# Generated by Django 5.2.16 on 2026-08-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0007_nonmember_aadhar_back_url_nonmember_aadhar_front_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datauploadlog",
            name="snapshot_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/master-snapshots/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="datauploadlog",
            name="snapshot_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
