# Generated by Django 5.2.16 on 2026-08-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0008_datauploadlog_snapshot_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datauploadlog",
            name="skipped_rows",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Rows whose record already existed and was therefore left untouched. A master upload inserts; it never overwrites (SRS §6.1.4).",
            ),
        ),
    ]
