# Generated by Django 5.2.16 on 2026-08-26 09:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0009_upload_skipped_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonmember",
            name="cattle_buffaloes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Buffaloes she keeps, as reported at registration."
            ),
        ),
        migrations.AddField(
            model_name="nonmember",
            name="cattle_cows",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Cows she keeps, as reported at registration."
            ),
        ),
        migrations.AddField(
            model_name="nonmember",
            name="daily_yield_litres",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Litres of milk a day across the herd, as reported at registration.",
                max_digits=6,
            ),
        ),
    ]
