# Generated by Django 5.2.16 on 2026-09-07 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0010_non_member_herd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Short identifier, e.g. ZONE1. Set once — reports and saved links use it.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "zone",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ZonePlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plant_code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("plant_name", models.CharField(blank=True, max_length=100)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plants",
                        to="masterdata.zone",
                    ),
                ),
            ],
            options={
                "db_table": "zone_plant",
                "ordering": ["plant_name"],
            },
        ),
    ]
