# Generated by Django 5.2.16 on 2026-09-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0011_zone_zoneplant"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonmember",
            name="client_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Device-generated id for a registration that may be retried (ADR 0003).",
                null=True,
                unique=True,
            ),
        ),
    ]
