# Generated by Django 5.2.16 on 2026-09-22 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterdata", "0012_non_member_client_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="datauploadlog",
            name="kept_rows",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Member rows whose mobile number differed from one the office had set, and where the office's number was kept. Counted among the skipped rows.",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="mobile_source",
            field=models.CharField(
                choices=[("sap", "SAP master"), ("office", "Set by the office")],
                db_index=True,
                default="sap",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="mobile_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="mobile_updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The admin who last set the number. The full history is the audit log.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
