"""
Sign-in codes from the office, for when the SMS does not arrive (accounts.SuperOTP).

This is a way into an account that does not go through the account's phone, so most of these
tests are about what it refuses: a code used twice, guessed at, outliving its ten minutes,
handed to somebody who can no longer sign in, or generated by an admin who cannot see the
person it is for.
"""

from __future__ import annotations

from datetime import timedelta

import pytest
from django.utils import timezone
from rest_framework.test import APIClient
from rest_framework_simplejwt.tokens import RefreshToken

from apps.accounts.models import PortalSection, Role, SuperOTP, User
from apps.core.models import AuditLog
from apps.masterdata.models import Zone, ZonePlant
from apps.stores.models import Store, StorePlant
from conftest import MaitFactory, MPPFactory

pytestmark = pytest.mark.django_db

ASK = "/api/v1/auth/otp/super/request/"
VERIFY = "/api/v1/auth/otp/verify/"
ADMIN = "/api/v1/admin/super-otp/"


def auth(user) -> APIClient:
    client = APIClient()
    client.credentials(HTTP_AUTHORIZATION=f"Bearer {RefreshToken.for_user(user).access_token}")
    return client


@pytest.fixture
def mait(db):
    mait = MaitFactory(name="Sunil Kumar")
    MPPFactory(mait=mait, plant_code="1101")
    return mait


@pytest.fixture
def office(db):
    return User.objects.create_user(
        username="office-codes",
        password="a-long-enough-password",
        full_name="Office",
        role=Role.ADMIN,
        portal_sections=[PortalSection.SUPER_OTP],
    )


def ask(mobile, reason=""):
    return APIClient().post(ASK, {"mobile_no": mobile, "reason": reason}, format="json")


def sign_in(mobile, code):
    return APIClient().post(VERIFY, {"mobile_no": mobile, "otp": code}, format="json")


def give_code(office, mait):
    ask(mait.mobile_no)
    row = SuperOTP.objects.get(user=mait.user, status=SuperOTP.Status.REQUESTED)
    response = auth(office).post(f"{ADMIN}{row.id}/issue/")
    assert response.status_code == 201, response.content
    return response.json()["code"]


class TestAsking:
    def test_a_registered_user_reaches_the_office(self, mait):
        response = ask(mait.mobile_no, "SMS not coming")
        assert response.status_code == 200
        row = SuperOTP.objects.get(user=mait.user)
        assert (row.state, row.reason, row.request_count) == ("waiting", "SMS not coming", 1)

    def test_an_unknown_number_gets_the_same_answer_and_nothing_is_written(self, mait):
        known = ask(mait.mobile_no)
        unknown = ask("9000000001")
        assert known.status_code == unknown.status_code == 200
        assert known.json() == unknown.json()
        assert SuperOTP.objects.count() == 1

    def test_asking_again_is_one_ask_counted_twice(self, mait):
        ask(mait.mobile_no)
        ask(mait.mobile_no)
        row = SuperOTP.objects.get(user=mait.user)
        assert row.request_count == 2

    def test_a_store_keeper_can_ask_too(self, db):
        store = Store.objects.create(code="BARSANA", name="Barsana depot")
        keeper = User.objects.create_user(
            username="keeper",
            full_name="Keeper",
            mobile_no="9123400001",
            role=Role.STORE,
            store=store,
        )
        ask(keeper.mobile_no)
        assert SuperOTP.objects.filter(user=keeper).exists()


class TestGenerating:
    def test_the_code_is_shown_once_and_stored_only_as_a_hash(self, office, mait):
        ask(mait.mobile_no)
        row = SuperOTP.objects.get(user=mait.user)
        response = auth(office).post(f"{ADMIN}{row.id}/issue/")

        code = response.json()["code"]
        assert len(code) == 6 and code.isdigit()
        assert response["Cache-Control"] == "no-store"
        row.refresh_from_db()
        assert row.code_hash and code not in row.code_hash
        listed = auth(office).get(ADMIN).content.decode()
        assert code not in listed

    def test_the_office_sees_who_it_is_and_the_number_to_call(self, office, mait):
        ask(mait.mobile_no)
        row = auth(office).get(ADMIN).json()[0]
        assert row["full_name"] == "Sunil Kumar"
        assert row["number_on_file"] == mait.mobile_no
        assert row["who"].startswith("Mait · ")
        assert row["state"] == "waiting"

    def test_a_new_code_revokes_the_last(self, office, mait):
        first = give_code(office, mait)
        second = (
            auth(office)
            .post(f"{ADMIN}issue-for-number/", {"mobile_no": mait.mobile_no}, format="json")
            .json()["code"]
        )
        if first != second:
            assert sign_in(mait.mobile_no, first).status_code == 400
        assert sign_in(mait.mobile_no, second).status_code == 200

    def test_nobody_signs_in_with_that_number(self, office):
        response = auth(office).post(
            f"{ADMIN}issue-for-number/", {"mobile_no": "9000000002"}, format="json"
        )
        assert response.status_code == 409

    def test_a_deactivated_account_is_not_handed_a_way_in(self, office, mait):
        ask(mait.mobile_no)
        row = SuperOTP.objects.get(user=mait.user)
        User.objects.filter(pk=mait.user_id).update(is_active=False)
        assert auth(office).post(f"{ADMIN}{row.id}/issue/").status_code == 409

    def test_an_ask_can_be_declined(self, office, mait):
        ask(mait.mobile_no)
        row = SuperOTP.objects.get(user=mait.user)
        response = auth(office).post(
            f"{ADMIN}{row.id}/decline/", {"reason": "Could not reach them"}, format="json"
        )
        assert response.json()["state"] == "declined"
        assert auth(office).post(f"{ADMIN}{row.id}/issue/").status_code == 409


class TestSigningIn:
    def test_the_office_code_signs_in_once(self, office, mait):
        code = give_code(office, mait)

        response = sign_in(mait.mobile_no, code)
        assert response.status_code == 200, response.content
        assert "access" in response.json()
        assert SuperOTP.objects.get(user=mait.user).status == SuperOTP.Status.USED
        assert AuditLog.objects.filter(
            action=AuditLog.Action.LOGIN, meta_json__method="super_otp"
        ).exists()

        assert sign_in(mait.mobile_no, code).status_code == 400

    def test_a_wrong_code_says_it_was_the_offices(self, office, mait):
        give_code(office, mait)
        response = sign_in(mait.mobile_no, "000000")
        assert response.status_code == 400
        assert "office" in response.json()["detail"]

    def test_five_wrong_tries_and_even_the_right_code_is_refused(self, office, mait, settings):
        code = give_code(office, mait)
        wrong = "111111" if code != "111111" else "222222"
        for _ in range(settings.SUPER_OTP_MAX_ATTEMPTS - 1):
            assert sign_in(mait.mobile_no, wrong).status_code == 400
        last = sign_in(mait.mobile_no, wrong)
        assert last.status_code == 429
        assert sign_in(mait.mobile_no, code).status_code in (400, 429)

    def test_a_code_past_its_ten_minutes_does_nothing(self, office, mait):
        code = give_code(office, mait)
        SuperOTP.objects.filter(user=mait.user).update(
            expires_at=timezone.now() - timedelta(seconds=1)
        )
        assert sign_in(mait.mobile_no, code).status_code == 400

    def test_the_code_only_opens_the_number_it_was_made_for(self, office, mait):
        code = give_code(office, mait)
        other = MaitFactory()
        assert sign_in(other.mobile_no, code).status_code == 400

    def test_the_sms_code_still_works_alongside(self, office, mait, settings):
        settings.DEV_FIXED_OTP_NUMBERS = [mait.mobile_no]
        give_code(office, mait)
        APIClient().post("/api/v1/auth/otp/send/", {"mobile_no": mait.mobile_no}, format="json")
        assert sign_in(mait.mobile_no, settings.DEV_FIXED_OTP_CODE).status_code == 200


class TestWhoMayGenerate:
    def test_without_the_section_there_is_no_screen(self, db, mait):
        clerk = User.objects.create_user(
            username="clerk",
            password="a-long-enough-password",
            full_name="Clerk",
            role=Role.ADMIN,
            portal_sections=[PortalSection.RATES],
        )
        assert auth(clerk).get(ADMIN).status_code == 403
        assert auth(mait.user).get(ADMIN).status_code == 403

    def test_a_zonal_manager_sees_and_serves_only_their_zone(self, db, mait):
        zone = Zone.objects.create(code="MATHURA", name="Mathura")
        ZonePlant.objects.create(zone=zone, plant_code="2202")
        manager = User.objects.create_user(
            username="zonal",
            password="a-long-enough-password",
            full_name="Zonal",
            role=Role.ADMIN,
            portal_sections=[PortalSection.SUPER_OTP],
        )
        manager.zones.add(zone)
        ask(mait.mobile_no)  # Sunil's MPP is in plant 1101, outside Mathura

        assert auth(manager).get(ADMIN).json() == []
        row = SuperOTP.objects.get(user=mait.user)
        assert auth(manager).post(f"{ADMIN}{row.id}/issue/").status_code == 404
        refused = auth(manager).post(
            f"{ADMIN}issue-for-number/", {"mobile_no": mait.mobile_no}, format="json"
        )
        assert refused.status_code == 404
        # Refused before anything was written: no code was made, and the ask still waits.
        row.refresh_from_db()
        assert row.status == SuperOTP.Status.REQUESTED
        assert not SuperOTP.objects.filter(status=SuperOTP.Status.ISSUED).exists()

    def test_a_keeper_is_in_their_stores_zone(self, db):
        zone = Zone.objects.create(code="MATHURA", name="Mathura")
        ZonePlant.objects.create(zone=zone, plant_code="2202")
        store = Store.objects.create(code="BARSANA", name="Barsana depot")
        StorePlant.objects.create(store=store, plant_code="2202")
        keeper = User.objects.create_user(
            username="keeper2",
            full_name="Keeper",
            mobile_no="9123400002",
            role=Role.STORE,
            store=store,
        )
        manager = User.objects.create_user(
            username="zonal2",
            password="a-long-enough-password",
            full_name="Zonal",
            role=Role.ADMIN,
            portal_sections=[PortalSection.SUPER_OTP],
        )
        manager.zones.add(zone)
        ask(keeper.mobile_no)
        rows = auth(manager).get(ADMIN).json()
        assert [row["who"] for row in rows] == ["Store keeper · Barsana depot"]
