# Generated by Django 5.2.16 on 2026-08-21 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_events", "0004_doses_and_consumables"),
        ("masterdata", "0007_nonmember_aadhar_back_url_nonmember_aadhar_front_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PregnancyCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "due_on",
                    models.DateField(
                        db_index=True,
                        help_text="Ninety days after the insemination, or a recheck's own date.",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pregnant", "Pregnant"),
                            ("not_pregnant", "Not pregnant"),
                            ("unsure", "Not sure"),
                        ],
                        db_index=True,
                        max_length=14,
                    ),
                ),
                ("checked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("photo_url", models.CharField(blank=True, max_length=500)),
                (
                    "calving_due_on",
                    models.DateField(
                        blank=True,
                        help_text="Set on a pregnant result and never recomputed after.",
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "client_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Minted on the handset when the result is recorded, so a result replayed from the offline queue is written once. A check is done in a yard with no signal as often as not (ADR 0003).",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ai_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pregnancy_checks",
                        to="ai_events.aievent",
                    ),
                ),
                (
                    "mait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pregnancy_checks",
                        to="masterdata.mait",
                    ),
                ),
                (
                    "rechecks",
                    models.ForeignKey(
                        blank=True,
                        help_text="The earlier check this one was booked by.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rechecked_by",
                        to="pregnancy.pregnancycheck",
                    ),
                ),
            ],
            options={
                "db_table": "pregnancy_check",
                "ordering": ["due_on", "id"],
                "indexes": [
                    models.Index(fields=["mait", "outcome", "due_on"], name="pd_mait_open_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("checked_at__isnull", True), ("outcome", "")),
                            models.Q(
                                models.Q(("outcome", ""), _negated=True),
                                ("checked_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="pregnancy_recorded_together",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("calving_due_on__isnull", True),
                            ("outcome", "pregnant"),
                            _connector="OR",
                        ),
                        name="pregnancy_calving_only_when_pregnant",
                    ),
                ],
            },
        ),
    ]
