# Generated by Django 5.2.16 on 2026-08-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pregnancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pregnancycheck",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pregnant", "Pregnant"),
                    ("not_pregnant", "Not pregnant"),
                    ("unsure", "Not sure"),
                    ("declined", "Owner declined"),
                ],
                db_index=True,
                max_length=14,
            ),
        ),
    ]
