# Generated by Django 5.2.16 on 2026-08-24 08:46

from django.db import migrations, models


def create_the_row(apps, schema_editor):
    """
    One row, unpriced.

    The table holds exactly one row and every reader expects to find it, so it is created here
    rather than by whoever first opens the Rates screen — a portal that has to cope with the
    row being absent is a portal with two states to get right instead of one.

    Both rates start at zero, which this codebase reads as *not priced* rather than as free:
    `pd_price_for` returns None and the app tells a Mait the visit is chargeable without
    naming a figure. Seeding a guess would be worse — a number nobody decided, quoted to a
    farmer in a yard.
    """
    PregnancyRate = apps.get_model("pregnancy", "PregnancyRate")
    PregnancyRate.objects.get_or_create(service="pd", defaults={"member_rate": 0, "non_member_rate": 0})


def drop_the_row(apps, schema_editor):
    apps.get_model("pregnancy", "PregnancyRate").objects.filter(service="pd").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pregnancy", "0002_alter_pregnancycheck_outcome"),
    ]

    operations = [
        migrations.CreateModel(
            name="PregnancyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.CharField(
                        choices=[("pd", "Pregnancy diagnosis")],
                        default="pd",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "member_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What a member is charged for one pregnancy diagnosis, in rupees. She hands over nothing: the dairy deducts it from her milk payment at the next payout. Zero means not priced, never free.",
                        max_digits=10,
                    ),
                ),
                (
                    "non_member_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What a non-member pays the Mait on the spot, in rupees. Zero means not priced, never free.",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "db_table": "pregnancy_rate",
            },
        ),
        migrations.AddField(
            model_name="pregnancycheck",
            name="amount_charged",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="What this visit cost, copied from the rate at the moment it was recorded rather than read back through today's rate. A price the farmer was quoted in a yard is a fact about that day; re-deriving it later would silently restate every past visit the next time the dairy changes what it charges. Null on a visit that was never performed — a refused check is not billed for — and on one recorded before anybody set a rate.",
                max_digits=10,
                null=True,
            ),
        ),
            migrations.RunPython(create_the_row, drop_the_row),
    ]
