# Generated by Django 5.2.9 on 2026-08-04 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("masterdata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mppoperatorassignment",
            name="mpp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operator_assignments",
                to="masterdata.mpp",
            ),
        ),
        migrations.AddField(
            model_name="mppoperatorassignment",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"role": "mpp_operator"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mpp_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role", "is_active"], name="user_role_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="mppoperatorassignment",
            constraint=models.UniqueConstraint(fields=("user", "mpp"), name="uniq_operator_mpp"),
        ),
    ]
