# Generated by Django 5.2.16 on 2026-09-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_logs_section"),
        ("masterdata", "0011_zone_zoneplant"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="zones",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which zones this account sees. Empty means the whole network — the default, and what every head-office account keeps.",
                related_name="users",
                to="masterdata.zone",
            ),
        ),
    ]
