# Generated by Django 5.2.16 on 2026-09-11 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_zones"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="For a store keeper, the one store whose counter they work. Empty for everyone else.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="keepers",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin / Back-office"),
                    ("mait", "Mait (Field Agent)"),
                    ("store", "Store keeper"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
