# Generated by Django 5.2.16 on 2026-09-11 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_stores_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mobile_no", models.CharField(db_index=True, max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Asked for"),
                            ("issued", "Code given"),
                            ("used", "Used to sign in"),
                            ("declined", "Declined"),
                            ("revoked", "Replaced by a newer code"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                    ),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("request_count", models.PositiveSmallIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("code_hash", models.CharField(blank=True, max_length=64)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("decline_reason", models.CharField(blank=True, max_length=200)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="super_otps_declined",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="super_otps_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="super_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "super_otp",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["mobile_no", "status"], name="super_otp_mobile_status_idx"
                    ),
                    models.Index(fields=["status", "-requested_at"], name="super_otp_queue_idx"),
                ],
            },
        ),
    ]
