# Generated by Django 5.2.16 on 2026-09-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_super_otp_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="superotp",
            name="ai_event_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="superotp",
            name="context",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="superotp",
            name="farmer_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="superotp",
            name="purpose",
            field=models.CharField(db_index=True, default="login", max_length=20),
        ),
        migrations.AddIndex(
            model_name="superotp",
            index=models.Index(
                fields=["mobile_no", "purpose", "status"], name="super_otp_step_idx"
            ),
        ),
    ]
