# Generated by Django 5.2.9 on 2026-08-04 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "mode",
                    models.CharField(
                        choices=[("ONLINE", "Online"), ("COD", "Cash on delivery")], max_length=6
                    ),
                ),
                ("member_otp_verified", models.BooleanField(default=False)),
                ("member_otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("utr_number", models.CharField(blank=True, db_index=True, max_length=40)),
                ("payment_screenshot_url", models.CharField(blank=True, max_length=255)),
                ("cod_otp_verified", models.BooleanField(default=False)),
                ("cod_otp_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                (
                    "ai_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="ai_events.aievent",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Mait login"),
                            ("payment_online", "Online payment authorisation"),
                            ("payment_cod", "COD confirmation"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("mobile_no", models.CharField(db_index=True, max_length=15)),
                ("otp_code_hash", models.CharField(max_length=64)),
                ("is_verified", models.BooleanField(default=False)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via", models.CharField(blank=True, max_length=20)),
                ("gateway_message_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_logs",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "otp_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status", "-created_at"], name="payment_status_time_idx"),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "ONLINE"), ("status", "verified"), _negated=True),
                    models.Q(
                        models.Q(("utr_number", ""), _negated=True),
                        models.Q(("payment_screenshot_url", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="online_verified_requires_utr_and_screenshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "COD"), ("status", "verified"), _negated=True),
                    models.Q(("cod_otp_verified", True), ("member_otp_verified", True)),
                    _connector="OR",
                ),
                name="cod_verified_requires_both_otps",
            ),
        ),
        migrations.AddIndex(
            model_name="otplog",
            index=models.Index(
                fields=["mobile_no", "purpose", "-created_at"], name="otp_mobile_purpose_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otplog",
            index=models.Index(fields=["expires_at", "is_verified"], name="otp_expiry_idx"),
        ),
    ]
