# Generated by Django 5.2.16 on 2026-08-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otplog",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Mait login"),
                    ("farmer_verify", "Farmer identity verification"),
                    ("payment_online", "Online payment authorisation"),
                    ("payment_cod", "COD confirmation"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
