# Generated by Django 5.2.16 on 2026-09-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_otplog_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("COD", "Cash on delivery"),
                    ("DEDUCT", "Deducted from milk payment"),
                ],
                max_length=6,
            ),
        ),
    ]
