# Generated by Django 5.2.16 on 2026-09-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaitPayoutScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheme",
                    models.CharField(
                        choices=[("ai", "Artificial insemination")],
                        default="ai",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "commission_per_ai",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Paid to the Mait for one completed insemination, in rupees.",
                        max_digits=10,
                    ),
                ),
                (
                    "monthly_fixed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="A flat monthly amount on top of the commission, paid only to a Mait who reached `fixed_min_ai` inseminations in the month. Zero switches it off.",
                        max_digits=10,
                    ),
                ),
                (
                    "fixed_min_ai",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Inseminations needed in the month to earn `monthly_fixed_amount`. The test is 'at least this many' — a Mait on exactly the threshold earns it.",
                    ),
                ),
                (
                    "straw_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Recovered from the payout for each semen straw issued to the Mait during the month, in rupees. Consumables are recovered at `Consumable.rate` instead — the Products screen owns those.",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "db_table": "mait_payout_scheme",
            },
        ),
    ]
