# Generated by Django 5.2.16 on 2026-09-11 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("indents", "0004_indenthandover_indentrequest_approved_at_and_more"),
        ("masterdata", "0012_non_member_client_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Short identifier, e.g. BARSANA. Set once — slips and saved links use it.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="e.g. Barsana depot.", max_length=100
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="The zone it sits in, for grouping on the portal. Does not decide which Maits it serves — its BMC/MCCs do.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stores",
                        to="masterdata.zone",
                    ),
                ),
            ],
            options={
                "db_table": "store",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StorePlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plant_code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("plant_name", models.CharField(blank=True, max_length=100)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plants",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "store_plant",
                "ordering": ["plant_name"],
            },
        ),
        migrations.CreateModel(
            name="StoreStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("straw", "Semen straw"), ("consumable", "Consumable")],
                        max_length=12,
                    ),
                ),
                ("breed", models.CharField(blank=True, default="", max_length=30)),
                ("product_ref_id", models.BigIntegerField(default=0)),
                ("qty_on_hand", models.IntegerField(default=0)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "store_stock",
            },
        ),
        migrations.CreateModel(
            name="StoreLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("receive", "Received into the store"),
                            ("issue", "Collected by a Mait"),
                            ("adjustment", "Manual adjustment"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "qty",
                    models.IntegerField(help_text="Positive for receipts, negative for handovers."),
                ),
                ("balance_after", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_movements",
                        to="indents.indenthandover",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger",
                        to="stores.storestock",
                    ),
                ),
            ],
            options={
                "db_table": "store_ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="storestock",
            constraint=models.UniqueConstraint(
                fields=("store", "product_type", "breed", "product_ref_id"), name="uniq_store_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="storestock",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_on_hand__gte", 0)), name="store_stock_never_negative"
            ),
        ),
    ]
