# Generated by Django 5.2.9 on 2026-08-04 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animals", "0001_initial"),
        ("inventory", "0001_initial"),
        ("masterdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_uuid",
                    models.UUIDField(
                        db_index=True,
                        help_text="Generated on the device before the first sync attempt.",
                        unique=True,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[("member", "Member"), ("non_member", "Non-member")], max_length=12
                    ),
                ),
                (
                    "straw_unique_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Denormalised from the batch so history survives any master-data cleanup.",
                        max_length=30,
                    ),
                ),
                ("ai_photo_url", models.CharField(blank=True, max_length=255)),
                (
                    "gps_lat",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "gps_lng",
                    models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("straw_verified", "Straw verified"),
                            ("photo_captured", "Photo captured"),
                            ("payment_pending", "Payment pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the AI was actually performed — set at photo capture, not at sync, so an offline event reports the real time.",
                        null=True,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_reason", models.CharField(blank=True, max_length=255)),
                (
                    "synced_from_offline",
                    models.BooleanField(
                        default=False,
                        help_text="True when the event reached the server via the offline queue.",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_events",
                        to="animals.animal",
                    ),
                ),
                (
                    "mait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_events",
                        to="masterdata.mait",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_events",
                        to="masterdata.member",
                    ),
                ),
                (
                    "mpp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_events",
                        to="masterdata.mpp",
                    ),
                ),
                (
                    "non_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_events",
                        to="masterdata.nonmember",
                    ),
                ),
                (
                    "semen_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_events",
                        to="inventory.semenbatch",
                    ),
                ),
            ],
            options={
                "db_table": "ai_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIEventTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_event_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ai_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_entries",
                        to="ai_events.aievent",
                    ),
                ),
            ],
            options={
                "db_table": "ai_event_timeline",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aievent",
            index=models.Index(fields=["mait", "-created_at"], name="aievent_mait_time_idx"),
        ),
        migrations.AddIndex(
            model_name="aievent",
            index=models.Index(fields=["mpp", "-created_at"], name="aievent_mpp_time_idx"),
        ),
        migrations.AddIndex(
            model_name="aievent",
            index=models.Index(fields=["status", "-created_at"], name="aievent_status_time_idx"),
        ),
        migrations.AddIndex(
            model_name="aievent",
            index=models.Index(fields=["completed_at"], name="aievent_completed_idx"),
        ),
        migrations.AddConstraint(
            model_name="aievent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("member__isnull", False), ("non_member__isnull", True)),
                    models.Q(("member__isnull", True), ("non_member__isnull", False)),
                    _connector="OR",
                ),
                name="ai_event_exactly_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="aievent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "completed"), _negated=True),
                    models.Q(("completed_at__isnull", False), ("semen_batch__isnull", False)),
                    _connector="OR",
                ),
                name="ai_event_completed_requires_straw",
            ),
        ),
        migrations.AddIndex(
            model_name="aieventtimeline",
            index=models.Index(fields=["ai_event", "created_at"], name="timeline_event_idx"),
        ),
    ]
