# Generated by Django 5.2.16 on 2026-08-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aievent",
            name="gps_source",
            field=models.CharField(
                choices=[
                    ("device", "The handset's own position"),
                    ("photo", "Written into the photograph"),
                ],
                default="device",
                help_text="Where the pin came from: the handset's own position at the moment of capture, or the coordinates written into a chosen photograph's EXIF. The second can be anywhere and any time, so it is never quietly presented as the first.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="aievent",
            name="photo_source",
            field=models.CharField(
                choices=[
                    ("camera", "Taken on the handset"),
                    ("gallery", "Chosen from the gallery"),
                ],
                default="camera",
                help_text="Whether the proof photo was taken through the app's own camera or chosen from the handset's gallery. A live capture is evidence that this animal was served at this place and time; a chosen one is a photograph of something, and the record has to be able to tell an auditor which it is holding.",
                max_length=10,
            ),
        ),
    ]
