# Generated by Django 5.2.16 on 2026-08-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_events", "0002_photo_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="aievent",
            name="stock_deducted",
            field=models.BooleanField(
                default=True,
                help_text="False on a record closed without a stock movement, because the straw it holds had already left the Mait's holding — used by another event, or corrected away underneath it. The insemination happened and the straw is spent either way; what this says is that the count cannot account for this event, so a report comparing straws against completions has the answer on the record.",
            ),
        ),
    ]
