# Generated by Django 5.2.16 on 2026-08-19 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_events", "0003_stock_deducted"),
        ("inventory", "0005_consumable_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="aievent",
            name="doses",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many straws of the breed this insemination used. Two in one visit is ordinary practice on a difficult animal, and both come off the Mait's flask — so the count is the event's, not an assumption of one held anywhere else.",
            ),
        ),
        migrations.CreateModel(
            name="AIEventConsumable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("qty", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumables",
                        to="ai_events.aievent",
                    ),
                ),
                (
                    "consumable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_event_uses",
                        to="inventory.consumable",
                    ),
                ),
            ],
            options={
                "db_table": "ai_event_consumable",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ai_event", "consumable"), name="ai_event_consumable_once"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("qty__gt", 0)), name="ai_event_consumable_qty"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIEventStraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="straws",
                        to="ai_events.aievent",
                    ),
                ),
                (
                    "semen_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_event_straws",
                        to="inventory.semenbatch",
                    ),
                ),
            ],
            options={
                "db_table": "ai_event_straw",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ai_event", "semen_batch"), name="ai_event_straw_once"
                    )
                ],
            },
        ),
    ]
